export interface ModuleDef {
  key: string
  number: number
  routePath: string
  routeName: string
  icon: string
  i18nKey: string
  functions: string[]
  group: 'core' | 'people' | 'business' | 'commission' | 'reporting' | 'platform' | 'support' | 'portal'
  // If omitted, module is visible to admin/staff/super_admin only. Include
  // 'agent' to also expose it to logged-in agents inside their portal.
  roles?: Array<'admin' | 'super_admin' | 'staff' | 'agent'>
  // If set, the module is only visible to users whose permission set
  // contains this key. Wildcard roles (super_admin, admin) bypass — they
  // always see everything. Layered on TOP of `roles` above.
  permission?: string
}

export const MODULES: ModuleDef[] = [
  // Unified access-control module — replaces the old `/auth` prototype
  // AND `/admin/roles`. Tabs: Users, Roles, MFA.
  {
    key: 'admin-access',
    number: 1,
    routePath: '/admin/access',
    routeName: 'admin-access',
    icon: 'pi pi-shield',
    i18nKey: 'adminAccessModule',
    group: 'platform',
    permission: 'admin.users',
    functions: [
      'จัดการผู้ใช้งานและกำหนดบทบาท',
      'สร้าง / แก้ไข / ลบ บทบาท',
      'กำหนดสิทธิ์แต่ละบทบาท (Permission)',
      'กำหนดสิทธิ์เพิ่ม / ปฏิเสธ ระดับผู้ใช้ (Override)',
      'เปิด / ปิด ระบบยืนยันตัวตน 2 ขั้นตอน (MFA)',
    ],
  },
  {
    key: 'tenant-settings',
    number: 2,
    routePath: '/settings',
    routeName: 'tenant-settings',
    icon: 'pi pi-cog',
    i18nKey: 'tenantSettings',
    group: 'core',
    functions: [
      'แก้ไขโปรไฟล์หน่วยงาน (ชื่อ โลโก้ ที่อยู่)',
      'ตั้งค่ารูปแบบค่าคอมมิชชั่น: as-earned (v1) vs advance (v2)',
      'ตั้งค่ารอบการจ่ายเงิน (รายสัปดาห์ / รายสองสัปดาห์ / รายเดือน)',
      'จัดการแบรนด์ของหน่วยงาน',
      'ดูบันทึกการตรวจสอบ (กิจกรรมทั้งหมดในหน่วยงาน)',
    ],
  },
  {
    key: 'carriers',
    number: 3,
    routePath: '/carriers',
    routeName: 'carriers',
    icon: 'pi pi-building',
    i18nKey: 'carriers',
    group: 'business',
    functions: [
      'สร้างบริษัทประกันภัย',
      'แก้ไขรายละเอียดบริษัทประกัน',
      'เปิด / ปิดการใช้งานบริษัทประกัน',
      'แสดงรายการ / ค้นหาบริษัทประกัน',
    ],
  },
  {
    key: 'products',
    number: 4,
    routePath: '/products',
    routeName: 'products',
    icon: 'pi pi-box',
    i18nKey: 'products',
    group: 'business',
    functions: [
      'สร้างผลิตภัณฑ์ (เชื่อมโยงกับบริษัทประกัน)',
      'แก้ไขเงื่อนไขผลิตภัณฑ์ (ความคุ้มครอง เบี้ยประกัน ระยะเวลา)',
      'กำหนดเงื่อนไขคุณสมบัติของผลิตภัณฑ์ (อายุ สุขภาพ ฯลฯ)',
      'เปิด / ปิดการใช้งานผลิตภัณฑ์',
      'แสดงรายการ / ค้นหาผลิตภัณฑ์ (กรองตามบริษัท ประเภท สถานะ)',
    ],
  },
  {
    key: 'contracts',
    number: 5,
    routePath: '/contracts',
    routeName: 'contracts',
    icon: 'pi pi-file-edit',
    i18nKey: 'contracts',
    group: 'business',
    functions: [
      'สร้างการแต่งตั้งกับบริษัทประกัน',
      'กำหนดตารางค่าคอมมิชชั่น (อัตราปีแรก อัตราต่ออายุ ต่อผลิตภัณฑ์)',
      'แก้ไขเงื่อนไขสัญญา',
      'ปิดใช้งานสัญญา',
      'แสดงรายการสัญญาทั้งหมดของหน่วยงาน',
    ],
  },
  {
    key: 'agents',
    number: 6,
    routePath: '/agents',
    routeName: 'agents',
    icon: 'pi pi-users',
    i18nKey: 'agents',
    group: 'people',
    functions: [
      'ลงทะเบียนตัวแทน (สร้างโปรไฟล์ กำหนดผู้แนะนำ)',
      'แก้ไขโปรไฟล์ตัวแทน',
      'ตั้งค่า / แก้ไขระดับสัญญา (เปอร์เซ็นต์ค่าคอมฯ)',
      'เปิด / ปิดการใช้งานตัวแทน',
      'โอนตัวแทนไปยังผู้แนะนำคนใหม่',
      'ดูสายงานตรงของตัวแทน',
      'ดูแผนผังสายงานทั้งหมด (recursive)',
      'ดูสายงานผู้แนะนำ (upline chain)',
      'จัดการใบอนุญาตตัวแทน (เลขที่ หน่วยงาน วันหมดอายุ)',
      'แจ้งเตือนเมื่อใบอนุญาตจะหมดอายุ',
      'สร้างลิงก์รับสมัครตัวแทน',
      'ตรวจสอบโทเค็นรับสมัครเมื่อสมัครสมาชิก',
      'กำหนดผู้แนะนำอัตโนมัติจากโทเค็นเมื่อลงทะเบียน',
      'ติดตามการใช้งานลิงก์รับสมัคร (คลิก สมัครสำเร็จ รอดำเนินการ)',
      'ยกเลิก / สร้างลิงก์รับสมัครใหม่',
      'ดูตัวแทนที่รับสมัครผ่านลิงก์ของฉัน',
    ],
  },
  {
    key: 'customers',
    number: 7,
    routePath: '/customers',
    routeName: 'customers',
    icon: 'pi pi-user',
    i18nKey: 'customers',
    group: 'people',
    functions: [
      'สร้างลูกค้า',
      'แก้ไขโปรไฟล์ลูกค้า',
      'ค้นหา / แสดงรายการลูกค้า (ตามชื่อ บัตรประชาชน โทรศัพท์ กรมธรรม์)',
      'ดูประวัติกรมธรรม์ของลูกค้า',
      'อัปโหลดเอกสาร KYC',
      'รวมรายการลูกค้าซ้ำ',
      'ปิดบัญชีลูกค้า',
      'สร้างลิงก์แนะนำลูกค้า (ต่อตัวแทน ต่อผลิตภัณฑ์/แคมเปญ)',
      'ตรวจสอบโทเค็นแนะนำเมื่อบันทึก lead หรือสร้างกรมธรรม์',
      'แท็กลูกค้ากับตัวแทนผู้แนะนำเมื่อสมัคร',
      'ติดตามการใช้งานลิงก์แนะนำลูกค้า',
      'ยกเลิก / สร้างลิงก์แนะนำใหม่',
      'ดูลูกค้าที่แนะนำผ่านลิงก์ของฉัน',
      'มอบหมายลูกค้าให้ตัวแทน (โดยผู้จัดการ/ผู้ดูแล)',
      'มอบหมายลูกค้าใหม่ (พร้อมเหตุผลและบันทึก)',
      'ดูลูกค้าทั้งหมดที่มอบหมายให้ตัวแทน',
      'ดูลูกค้าที่ยังไม่ได้รับมอบหมาย',
      'ดูประวัติการมอบหมายของลูกค้า',
    ],
  },
  {
    key: 'policies',
    number: 8,
    routePath: '/policies',
    routeName: 'policies',
    icon: 'pi pi-file',
    i18nKey: 'policies',
    group: 'business',
    functions: [
      'สร้างใบเสนอราคา (เชื่อมลูกค้า → ผลิตภัณฑ์ → ตัวแทนผู้ขาย)',
      'แปลงใบเสนอราคาเป็นใบสมัคร',
      'ส่งใบสมัครไปยังบริษัทประกัน',
      'ออกกรมธรรม์ (บันทึกเลขกรมธรรม์ + วันคุ้มครอง)',
      'แก้ไขรายละเอียดกรมธรรม์',
      'บันทึกการชำระเบี้ยประกัน',
      'ต่ออายุกรมธรรม์ (สร้างเหตุการณ์ต่ออายุ)',
      'ยกเลิกกรมธรรม์ (เริ่ม clawback)',
      'กรมธรรม์หลุดจากการไม่ชำระเงิน (เริ่ม clawback)',
      'นำกรมธรรม์ที่หลุดกลับมาใช้งาน',
      'ดูประวัติเหตุการณ์ของกรมธรรม์',
      'อัปโหลดเอกสารกรมธรรม์',
      'ค้นหา / กรองกรมธรรม์ (ตามสถานะ ตัวแทน ผลิตภัณฑ์ ลูกค้า ช่วงวันที่)',
    ],
  },
  {
    key: 'renewal-pipeline',
    number: 8,
    routePath: '/policies/expiring',
    routeName: 'policies-expiring',
    icon: 'pi pi-clock',
    i18nKey: 'renewalPipeline',
    group: 'business',
    functions: [
      'คิวกรมธรรม์ที่จะครบกำหนด (30 / 60 / 90 / 180 วัน)',
      'ไฮไลต์กรมธรรม์ด่วน (≤7 วัน)',
      'สรุปยอด premium ที่ต้องต่ออายุในช่วงเวลา',
    ],
  },
  // NOTE: `commission-engine` and `commission-ledger` module entries removed
  // with the MGM rewrite. New MGM-based equivalents will be added when their
  // pages ship (PR-D and later).
  {
    key: 'rebate-reconciliation',
    number: 10,
    routePath: '/commissions/rebates',
    routeName: 'commission-rebates',
    icon: 'pi pi-calculator',
    i18nKey: 'rebateReconciliation',
    group: 'commission',
    functions: [
      'ตรวจสอบ Calculated vs Actual บนสามขา — InH / OV / Agent',
      'ระบุ mismatch (|Δ| > 1 THB) เพื่อ audit',
      'ดูประวัติ rebate ledger ต่อกรมธรรม์',
    ],
  },
  // NOTE: `payouts` module entry removed with the MGM rewrite. New payout
  // module will be added when PR-D's admin surface ships.
  {
    key: 'reports',
    number: 12,
    routePath: '/reports',
    routeName: 'reports',
    icon: 'pi pi-chart-line',
    i18nKey: 'reports',
    group: 'reporting',
    functions: [
      'รายงานยอดขายของตัวแทน (กรมธรรม์ เบี้ย ค่าคอมฯ)',
      'รายงานทีม / สายงาน (รวมยอดตามผู้แนะนำ)',
      'รายงานบัญชีค่าคอมฯ (ตามตัวแทนหรือช่วงเวลา)',
      'รายงานประวัติการจ่ายเงิน',
      'รายงาน clawback (พร้อมเหตุผลและกรมธรรม์ต้นเหตุ)',
      'รายงานสถานะกรมธรรม์ (ใช้งาน หลุด ยกเลิก ตามบริษัท/ผลิตภัณฑ์/ตัวแทน)',
      'รายงานการกระทบยอดกับบริษัทประกัน (v2)',
      'แดชบอร์ดภาพรวมหน่วยงาน',
      'รายงานผลการแนะนำ (ลิงก์ที่แชร์ คลิก สมัครสำเร็จ โบนัส)',
    ],
  },
  {
    key: 'notifications',
    number: 13,
    routePath: '/notifications',
    routeName: 'notifications',
    icon: 'pi pi-bell',
    i18nKey: 'notifications',
    group: 'platform',
    functions: [
      'แจ้งเตือนต่ออายุกรมธรรม์ (ถึงตัวแทน + ลูกค้า กำหนดล่วงหน้าได้)',
      'แจ้งเตือนค้างชำระเบี้ย (ถึงตัวแทน)',
      'แจ้งเตือนเมื่อจ่ายค่าคอมฯ สำเร็จ (ถึงตัวแทน)',
      'แจ้งเตือนเมื่อมี clawback (ถึงตัวแทน)',
      'แจ้งเตือนใบอนุญาตตัวแทนจะหมดอายุ',
      'แจ้งเตือนกรมธรรม์ใหม่ที่ออก (ถึงตัวแทน + ลูกค้า)',
    ],
  },
  {
    key: 'import-failures',
    number: 14,
    routePath: '/settings/import-failures',
    routeName: 'settings-import-failures',
    icon: 'pi pi-exclamation-triangle',
    i18nKey: 'importFailures',
    group: 'platform',
    functions: [
      'คิว triage สำหรับ legacy applications ที่ไม่สามารถ import ได้',
      'กรองตาม reason (missing_client / agent / product / company)',
      'ดู raw source row เพื่อวิเคราะห์',
      'บันทึก resolution notes และ mark resolved',
    ],
  },
  {
    key: 'platform-admin',
    number: 14,
    routePath: '/admin',
    routeName: 'platform-admin',
    icon: 'pi pi-th-large',
    i18nKey: 'platformAdmin',
    group: 'platform',
    functions: [
      'แสดงรายการ / ค้นหาหน่วยงานทั้งหมด (tenants)',
      'ระงับ / เปิดการใช้งานหน่วยงาน',
      'แอบสวมรอย (impersonate) เพื่อให้การสนับสนุน',
      'จัดการแค็ตตาล็อกกลางของบริษัทและผลิตภัณฑ์',
      'ดูตัวชี้วัดการใช้งานทั่วแพลตฟอร์ม',
      'จัดการการสมัครสมาชิก / การเรียกเก็บเงินต่อหน่วยงาน',
    ],
  },
  {
    key: 'agent-support',
    number: 15,
    routePath: '/support',
    routeName: 'agent-support',
    icon: 'pi pi-headphones',
    i18nKey: 'agentSupport',
    group: 'support',
    functions: [
      'แดชบอร์ดติดตามเคสที่ค้างในทุกขั้นตอนของกรมธรรม์',
      'การ์ดสรุป: รอใบเสนอราคา / SLA เสี่ยง / ต้องดำเนินการ / ปิดในเดือนนี้',
      'คิวเคสสดพร้อมตัวกรองสถานะและค้นหาด่วน',
      'แผงรายละเอียดเคสพร้อม timeline + อัปโหลดเอกสาร + บันทึก',
    ],
  },
  {
    key: 'agent-operation-support',
    number: 16,
    routePath: '/ops',
    routeName: 'agent-operation-support',
    icon: 'pi pi-sliders-h',
    i18nKey: 'agentOperationSupport',
    group: 'support',
    functions: [
      'แดชบอร์ดทีมหลังบ้าน: ตัวแทนรอตรวจสอบ / ใบอนุญาตหมดอายุ / อัปเดตจากบริษัทประกัน',
      'คิวอนุมัติตัวแทนพร้อมตรวจเอกสารและอนุมัติเร็ว',
      'คอนโซลข้อมูลกลาง: บริษัทประกัน / เรท / กฎค่าคอมฯ / audit log',
      'การแจ้งเตือนระบบ: sync error, API drop',
    ],
  },
  // ── Phase 5 — Quotation module. Visible to admin/staff + agents ────────
  {
    key: 'quotes',
    number: 51,
    routePath: '/quotes',
    routeName: 'quotes',
    icon: 'pi pi-calculator',
    i18nKey: 'quotes',
    group: 'business',
    roles: ['admin', 'super_admin', 'staff', 'agent'],
    functions: [],
  },
  // ── Admin oversight (Phase 4) — admin/super_admin only ─────────────────
  {
    key: 'admin-agent-approvals',
    number: 90,
    routePath: '/admin/agent-approvals',
    routeName: 'admin-agent-approvals',
    icon: 'pi pi-user-plus',
    i18nKey: 'adminAgentApprovals',
    group: 'platform',
    functions: [],
  },
  {
    key: 'admin-downline-tree',
    number: 91,
    routePath: '/admin/downline-tree',
    routeName: 'admin-downline-tree',
    icon: 'pi pi-sitemap',
    i18nKey: 'adminDownlineTree',
    group: 'platform',
    functions: [],
  },
  {
    key: 'admin-motor-tariffs',
    number: 93,
    routePath: '/admin/motor-tariffs',
    routeName: 'admin-motor-tariffs',
    icon: 'pi pi-car',
    i18nKey: 'adminMotorTariffs',
    group: 'platform',
    functions: [],
  },
  // Phase 8a — operational reports (admin/staff)
  {
    key: 'report-freelook',
    number: 80,
    routePath: '/reports/freelook',
    routeName: 'report-freelook',
    icon: 'pi pi-eye',
    i18nKey: 'reportFreelook',
    group: 'reporting',
    functions: [],
  },
  {
    key: 'report-cancellations',
    number: 81,
    routePath: '/reports/cancellations',
    routeName: 'report-cancellations',
    icon: 'pi pi-ban',
    i18nKey: 'reportCancellations',
    group: 'reporting',
    functions: [],
  },
  {
    key: 'report-mailing',
    number: 82,
    routePath: '/reports/mailing',
    routeName: 'report-mailing',
    icon: 'pi pi-envelope',
    i18nKey: 'reportMailing',
    group: 'reporting',
    functions: [],
  },
  {
    key: 'report-payments',
    number: 83,
    routePath: '/reports/payments',
    routeName: 'report-payments',
    icon: 'pi pi-credit-card',
    i18nKey: 'reportPayments',
    group: 'reporting',
    functions: [],
  },
  // ── Agent Portal (only visible when user.role === 'agent') ─────────────
  {
    key: 'portal-dashboard',
    number: 100,
    routePath: '/portal',
    routeName: 'portal-dashboard',
    icon: 'pi pi-home',
    i18nKey: 'portalDashboard',
    group: 'portal',
    roles: ['agent'],
    functions: [],
  },
  {
    key: 'portal-profile',
    number: 101,
    routePath: '/portal/profile',
    routeName: 'portal-profile',
    icon: 'pi pi-user',
    i18nKey: 'portalProfile',
    group: 'portal',
    roles: ['agent'],
    functions: [],
  },
  {
    key: 'portal-referral',
    number: 102,
    routePath: '/portal/referral',
    routeName: 'portal-referral',
    icon: 'pi pi-users',
    i18nKey: 'portalReferral',
    group: 'portal',
    roles: ['agent'],
    functions: [],
  },
  {
    key: 'portal-settings',
    number: 103,
    routePath: '/portal/settings',
    routeName: 'portal-settings',
    icon: 'pi pi-cog',
    i18nKey: 'portalSettings',
    group: 'portal',
    roles: ['agent'],
    functions: [],
  },
  {
    key: 'portal-earnings',
    number: 104,
    routePath: '/portal/earnings',
    routeName: 'portal-earnings',
    icon: 'pi pi-wallet',
    i18nKey: 'portalEarnings',
    group: 'portal',
    roles: ['agent'],
    functions: [],
  },
]

export const MODULE_GROUPS: { key: ModuleDef['group']; labelTh: string }[] = [
  { key: 'core', labelTh: 'ระบบหลัก' },
  { key: 'business', labelTh: 'ข้อมูลธุรกิจ' },
  { key: 'people', labelTh: 'บุคลากรและลูกค้า' },
  { key: 'commission', labelTh: 'ค่าคอมมิชชั่นและจ่ายเงิน' },
  { key: 'reporting', labelTh: 'รายงานและแจ้งเตือน' },
  { key: 'platform', labelTh: 'แพลตฟอร์ม' },
  { key: 'support', labelTh: 'ฝ่ายสนับสนุน' },
  { key: 'portal', labelTh: 'พอร์ทัลตัวแทน' },
]
